# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('desc', models.CharField(max_length=300, verbose_name='\u4e1a\u52a1\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u4ea7\u54c1\u8be6\u60c5')),
                ('degree', models.CharField(choices=[('lw', '\u52b3\u52a1'), ('cw', '\u8d22\u52a1')], max_length=4)),
                ('max_price', models.FloatField(max_length=10, verbose_name='\u6700\u9ad8\u4ef7\u683c')),
                ('min_price', models.FloatField(max_length=10, verbose_name='\u6700\u4f4e\u4ef7\u683c')),
                ('image', models.ImageField(upload_to='productionimage/%Y/%m', verbose_name='\u4ea7\u54c1\u5c01\u9762\u56fe')),
                ('index', models.IntegerField(max_length=100, verbose_name='\u4ea7\u54c1\u6392\u5e8f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u670d\u52a1',
                'verbose_name_plural': '\u4ea7\u54c1\u670d\u52a1',
            },
        ),
    ]
