# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='index',
            field=models.IntegerField(default=100, verbose_name='\u4ea7\u54c1\u6392\u5e8f'),
        ),
    ]
