# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 07:38
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20171214_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9\t'),
        ),
    ]
