# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion

import DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20180108_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='\u5ba2\u6237')),
                ('comments', DjangoUeditor.models.UEditorField(default='', verbose_name='\u8bc4\u8bba\u5185\u5bb9')),

                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u8bc4\u8bba',
                'verbose_name_plural': '\u5ba2\u6237\u8bc4\u8bba',
            },
        ),
        migrations.AlterField(
            model_name='production',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='customercomments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production', verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
    ]
