# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 15:51
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20180121_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='detail',
            field=DjangoUeditor.models.UEditorField(max_length=200, verbose_name='\u5185\u5bb9'),
        ),
    ]
