# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 14:30
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=DjangoUeditor.models.UEditorField(verbose_name='\u4fe1\u606f'),
        ),
    ]
