# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 18:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180206_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100, verbose_name='\u5ba2\u6237\u8ba2\u5355')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8ba2\u5355\u521b\u5efa\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u8ba2\u5355',
                'verbose_name_plural': '\u5ba2\u6237\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='MyServiceMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceman', models.CharField(max_length=20, verbose_name='\u79c1\u4eba\u5ba2\u670d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8ddf\u5355\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u79c1\u4eba\u5ba2\u670d',
                'verbose_name_plural': '\u79c1\u4eba\u5ba2\u670d',
            },
        ),
    ]
