# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myorder_myserviceman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '\u7528\u6237\u6d88\u606f', 'verbose_name_plural': '\u7528\u6237\u6d88\u606f'},
        ),
    ]
